development:
  adapter: postgresql
  encoding: unicode
  database: loople_development
  host: localhost
  pool: 5
<<<<<<< HEAD
  username: annehomann
=======
  username: kriss
  password:
>>>>>>> 9140b434237f59a0118fd56029e24a44dbcebce0

